steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build Image'
  args: [ 'build', '-t', 'sample_ci_image:latest', '.' ]

- name: 'sample_ci_image:latest'
  id: 'Run Tests'
  entrypoint: 'bash'
  allowFailure: true
  # It will create the file with content 'Error', then runs the tests.
  # If tests are success, modify the content of file to 'Success'.
  # If tests failed, this step is not marked as success or failure and the next steps will be executed.
  args: 
    - -c
    - |
      echo 'Error' > /workspace/step.log && \
      python -m pytest tests/ && \
      echo 'Success' > /workspace/step.log

    
- name: 'gcr.io/cloud-builders/docker'
  id: 'Final Step'
  entrypoint: 'bash'
  args:
    - -c
    - |
      file_content=$(cat /workspace/step.log)
      if [[ "$file_content" == "Success" ]]; then
        echo "Build Success"
      else
        echo "Build Failed"
        exit 1
      fi
